version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: cloudops_app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - env/app.env
    depends_on:
      - mysql
    networks:
      - cloudops_net

  mysql:
    image: mysql:8.0
    container_name: cloudops_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: school_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cloudops_net

volumes:
  mysql_data:

networks:
  cloudops_net:
